---
name: Perform Markdown Linter Run on README

on:
  pull_request:
    branches: ["main"]

  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Print list of files to perform linter run at
        run: |
          echo "$(git ls-files '*.md')"

      - name: Run markdown-lint
        uses: articulate/actions-markdownlint@v1.1.0
        with:
          files: '**/*.md'
