---
name: Perform Markdown Linter Run on README

on:
  pull_request:
    branches: ["main"]

  push:
    branches: ["main"]

jobs:
  build:
    - uses: actions/checkout@master

    - name: Run markdown-lint
      uses: articulate/actions-markdownlint@v1.1.0
      with:
        files: README.md
