---
name: Perform Python Linter Run

on:
  pull_request:
    branches: ["main"]

  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint


      - name: Analyse the python module code
        run: |
          for python_file in $(git ls-files -- '*.py' ':!:*.test.py');
            do
            echo "Analysing ${python_file} with pylint";
            pylint --rcfile pipeline_config/.pylintrc "${python_file}";
            done

      - name: Analyse the python unit test code with pylint
        run: |
          for python_file in $(git ls-files -- '*.test.py');
            do
            echo "Analysing ${python_file} with pylint";
            pylint --rcfile pipeline_config/.pylintrc_tests "${python_file}";
            done
